title: vbaobao_blog
email: your-email@example.com
description: >- # this means to ignore newlines until 'baseurl:'
  A static site engineering blog.
domain: 'vbaobao.github.io'
baseurl: ''
url: 'https://vbaobao.github.io' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vbao_is_here
github_username:  vbaobao

# Build settings
encoding: UTF-8
destination: public
plugins:
  - jekyll-feed
markdown: kramdown
highlighter: rouge
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Build vars
social_links:
  linkedin: 'https://www.linkedin.com/in/vibao/'
  github: 'https://github.com/vbaobao'
  email: ''

colors:
  black: '#1a1b20'
  dark-grey: '#424450'
  light-grey: '#7a7a7a'
  white: '#e2e3e7'
  red: '#ff5f61'
  purple: '#946bf4'
  yellow: '#ffc541'
  black-transparent: 'rgba(26, 27, 32, 0.85)'
  dark-grey-transparent: 'rgba(66, 68, 80, 0.85)'