title: vbaobao_blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A static site engineering blog.
domain: "vbaobao.github.io"
baseurl: ""
url: "https://vbaobao.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: vbao_is_here
github_username:  vbaobao

# Build settings
encoding: UTF-8
destination: public
source: src
plugins:
  - jekyll-feed
markdown: kramdown
highlighter: rouge
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  projects:
    output: true